#! /bin/bash

exec > pull.log 2>&1
git pull origin master
python ./sched.py pinto-american | sort -u > pinto-american.csv &
python ./sched.py mustang-american | sort -u > mustang-american.csv &
python ./sched.py bronco-american | sort -u > bronco-american.csv &
python ./sched.py bronco-national | sort -u > bronco-national.csv &
python ./sched.py pony-american | sort -u > pony-american.csv &
python ./sched.py pony-national | sort -u > pony-national.csv &
wait
find . -size 0 -name \*.csv -print > /var/tmp/sizes
if [ -s /var/tmp/sizes ]; then 
  git -f checkout `cat /var/tmp/sizes`
fi
git add *-*.csv
git commit -m "`date '+%Y%m%d@%H%M update'`"
git push origin 2017
